services:
  rinhadebackend-api-1: &api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - CONNECTION_STRING=Host=postgres;Port=5432;Username=rinha;Password=rinha;Database=rinha
    networks:
      - backend
      - payment-processor
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "110MB"

  rinhadebackend-api-2:
    <<: *api

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=rinha
    command: >-
      postgres -c max_connections=400
               -c shared_buffers=512MB
               -c synchronous_commit=off
               -c fsync=off
               -c full_page_writes=off
               -c wal_level=minimal
               -c max_wal_senders=0
               -c max_wal_size=4GB
               -c checkpoint_timeout=30min
               -c log_min_duration_statement=-1
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    ports:
      - "5432:5432"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "1000MB"

  nginx:
    image: nginx:1.27.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "9999:9999"
    networks:
      - payment-processor
      - backend
    depends_on:
      - rinhadebackend-api-1
      - rinhadebackend-api-2
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "30MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
  