services:
  rinhadebackend-api-1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
    ports:
      - "9999:8080"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
  