// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RinhaDeBackend.Infra;

#nullable disable

namespace RinhaDeBackend.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250725063956_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RinhaDeBackend.Domain.ProcessPaymentDto", b =>
                {
                    b.Property<Guid>("correlationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("requestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("correlationId");

                    b.ToTable("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
